# Generated by Django 4.1.2 on 2022-10-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_users_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='lightbulb_outline', max_length=100, verbose_name='Icon'),
        ),
    ]
