# Generated by Django 4.1.2 on 2022-10-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0001_initial"),
        ("course", "0005_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="modules",
            field=models.ManyToManyField(to="module.module"),
        ),
    ]
