# Generated by Django 4.1.2 on 2022-10-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assignment',
            field=models.ManyToManyField(to='assignment.assignment'),
        ),
    ]
