# Generated by Django 4.1.2 on 2022-11-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='assignment',
            new_name='assignments',
        ),
    ]
